version: '{build}'

skip_tags: true

install: []

environment:
  matrix:
    - VSVERSION: Visual Studio 11
    - VSVERSION: Visual Studio 12
    - VSVERSION: Visual Studio 14

platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release

build_script:
  - md build
  - cd build
  - if "%PLATFORM%"=="x64" cmake -G "%VSVERSION% Win64" ..
  - if "%PLATFORM%"=="Win32" cmake -G "%VSVERSION%" ..
  - msbuild /m /p:Configuration="%CONFIGURATION%" /p:Platform="%PLATFORM%" spirv-tools.sln
