//
// Created by antonikarp on 7/17/20.
//

#ifndef SPIRV_TOOLS_TRANSFORMATION_REPLACE_COPYOBJECT_WITH_STORE_LOAD_H
#define SPIRV_TOOLS_TRANSFORMATION_REPLACE_COPYOBJECT_WITH_STORE_LOAD_H

#endif  // SPIRV_TOOLS_TRANSFORMATION_REPLACE_COPYOBJECT_WITH_STORE_LOAD_H
